export function parseUnits(input: string): any;
export function formatUnits(source: string): string;
export function createUnitsEvaluator(): (raw: string, scope: any, locals?: any) => any;
export function renderUnits(ast: any, scope: any, options?: any): any;
export function createUnitsRenderer(host: any): { render: (ast: any, scope: any, options?: any) => any };
export function normalizeDomTree(input: any): any;
export function normalizeA11yTree(input: any): any;
export function serializeAgentTree(irTree: any, options?: any): any;
export function normalizeIrNode(node: any, defaults?: any): any;
export function compileTransformProgram(astOrSource: any, options?: any): any;
export function runTransformProgram(programOrSource: any, irTree: any, context?: any): any;
export function scoreProgram(args: { inputTree: any; outputTree: any; expectations?: any }): any;
export function verifyProgram(score: any, gates?: any): any;
export function computeProgramFingerprint(programSource: string): string;
export function createVerifiedProgramMetadata(args: any): any;
export function loadVerifiedLibrary(directory: string, options?: any): Promise<any[]>;
export function dedupeLibraryEntries(entries?: any[]): any[];
export function selectBestVerifiedProgram(entries?: any[], options?: any): any;
export function writeVerifiedProgram(args: any): Promise<any>;
export function rollbackProgram(args: any): Promise<any>;
export function evaluateProgramOnDataset(args: any): Promise<any>;
export function runSynthesisLoop(options?: any): Promise<any>;
export function findChangedRange(prev: string, next: string): { start: number; endPrev: number; endNext: number };
export function findSmallestEnclosingNode(ast: any, start: number, end: number): any;
export function incrementalParse(prevAst: any, prevSource: string, nextSource: string): any;
